# -*- coding: utf-8 -*-
"""Listasydiccionarios.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aAcdLAWxGOBvWc6n-OboIfCjTN6TW5ZU
"""

#lista

frutas=["manzana", "pera", "mango", "banano", "pitalla", "aguacate"]
print(frutas[1])

frutas[2]="mango"
print(frutas[2])

print(*frutas)

frutas.append("platano")
print(*frutas)

frutas.pop()
print(*frutas)

frutas.remove("pera")
print(*frutas)

print(len(frutas))

#diccionario

contactos={
    "maria": " 300 313 6901 " ,
    "paola": " 3012456787 ",
    "hector": " 3025647689 ",
    "santiago": "3453245678"
}
print("llamar a hector: ", contactos["hector"])

contactos["camila "]="3105678967"
print(contactos)

contactos["santiago"]="3224567890"

del contactos["camila "]
print(contactos)

#lista de tareas

print("Tareas")
tareas=["sus tareas son: \n 1 hacer aseo \n 2 Ir a trabajar \n 3 Esctudiar"]
print(tareas[0])

tareas.append("\n 4 limpiar vidrios")
print(*tareas)

tareas.remove("\n 4 limpiar vidrios")
print(*tareas)

frutas= {
    "manzana" : "1.500",
    "banano" : "2.200",
    "mango" : "4.500"
}
print(frutas)

frutas["mango"]= "3.000"
print(frutas)

frutas["limones"]= "1.100L"
print(frutas)

del frutas["banano"]
print(*frutas.keys(), *frutas.values())
print(frutas)

#diccionarios anidados
contactos={
    "andres":{
        "telefono" : ["300 313 6901", 3018694567],
        "correo": "andresito23@gmail.com",
        "direccion": {
            "carrera": "32",
            "barrio": "el jardin",
            "ciudad": "cali"
        }
    },
    "paula":{
        "telefono": ["3025469382"],
        "correo": ["pausam0511@gmail.com", "paular@hotmail.com", "pausam89@yahoo.com"],
        "direccion":{
            "calle": "44",
            "barrio": "salomia",
            "ciudad": "cali"
        }

    },
    "hector":{
        "telefono": ["3124567832"],
        "correo": "hectorfabiof@hotmail.com",
        "direccion": {
            "calle": "56",
            "barrio": "cuidad guavinas",
            "ciudad": "yumbo"
        }
    }

}

print(contactos)

contactos["tatiana"]={
    "telefono": [3167653894],
    "correo": "tatiana@gmail.com",
    "direccion": {
        "barrio": "belalcazar"
    }

}
print(contactos)

contactos["arali"]= {
    "telefono": [3003138900],
    "direccion": {
        "carrera": "32",
        "calle": "26b",
        "barrio": "el jardin",
        "ciudad": "cali"

    }
}

print(contactos)
print(*contactos)

print("El telefono de arali es: ", contactos["arali"]["telefono"])
print("El segundo telefono de andres es: ", contactos["andres"]["telefono"][1])
print("la ciudad de andres es: ", contactos["andres"]["direccion"]["ciudad"]) #cuidadandres

telefonosandres=contactos["andres"]["telefono"]
print(telefonosandres)

#for variable/contador=0 in limite(<11)

for telefono in telefonosandres:
  print("Los telefonos de andres son: ", telefono)

for s, telefono in enumerate (telefonosandres, start=1):
  print(f"Los telefonos de andres son: {s}= ", telefono)


correospaula= contactos["paula"]["correo"]

for c, correo in enumerate (correospaula, start=1):
  print(f"Los correos de paula son: {c}= ", correo)

contactos["andres"]["cumpleaños"]="28 de mayo"  #agregar una clave o campo nuevo a andres
print("El cumple años de andres es: ", *contactos["andres"]["cumpleaños"])

contactos["andres"]["Fecha de nacimiento"]=[28, "mayo", 1981]
print("La fecha de nacimiento de andres es: ", *contactos["andres"]["Fecha de nacimiento"])

yearNacimiento=contactos["andres"]["Fecha de nacimiento"][2]
if yearNacimiento >= 18:
  print("andres ya esta viejo")
else:
  print("andres esta en pañales todavia")

del contactos["hector"] #eliminar contacto
print(*contactos)

contactos["paula"]["correo"].remove("pausam89@yahoo.com")
print(*contactos["paula"]["correo"])